### ISSUE TITLE
icon problem and how to add the next button

### ISSUE THREAD

**Issue by defaultbr** [worker8/TourGuide#3] opened 2015-07-15 15:21 UTC
i loved this tour guide, thx worker8!

sorry the silly question, i know how to add the next button to the layout, but it get "darker", thats because the overlay color to make a "disabled screen" and give lighting to where the pointer is. How can i make the button above/below the tooltip or another position but without getting dark, i tried adding another tourguide just to the button, but it add another "darker" to all the layout making the white pointer a little gray..

or is there another "good" approach for handling the tooltip in sequence and i dont know?

and about the icon problem, when i add the tourguide to the gradle, my manifest get a conflict:

android:icon="myicon"is also present at com.github.worker8:tourguide:1.0.10-SNAPSHOT:13:9 value=(@drawable/ic_launcher1)

i already tried the android:replace icon but without results

not related to the problem, but it was like I was doing:

1) User open the app for the first time(check the SharedPrefs)
2) Load a new TourGuide to the first element i want to teach and add the button next in the middle of the screen
3) for each click on the button call a function called `nextTip()` and for each click it do a `tipCount++;` and inside the function `nextTip()` it check the number and set the actual tour to a new TourGuide... related to the position(after a `cleanUp()` ofc)

thats the correct approach or there is a kind of `actualTour.addTour(new TourGuide...)`  and some kind of `actualTour.displayNextTour()`;

thx the nice tourGuide ;)

**Comment by worker8** [comment] 2015-07-16 03:17
@defaultbr thanks for writing up, glad that you like it!

> sorry the silly question, i know how to add the next button to the layout, but it get "darker", thats because the overlay color to make a "disabled screen" and give lighting to where the pointer is. How can i make the button above/below the tooltip or another position but without getting dark, i tried adding another tourguide just to the button, but it add another "darker" to all the layout making the white pointer a little gray..

Are you trying to use TourGuide on 2 buttons, but 1 of the `Pointer` is covered up by the `Overlay` of another TourGuide, like this shown below?
![Is it like this?](http://i.imgur.com/f5DiLNx.png)

If that's not the case, can you attached a screenshot? I think that'll definitely help :+1: 

> or is there another "good" approach for handling the tooltip in sequence and i dont know?

There are currently no better approach to handle tooltip in sequence. :( The only way now is to create a new TourGuide for every button. It's much better to use 1 single mTourGuideHandler throughout a tour. It's in the [Roadmap](https://github.com/worker8/TourGuide/wiki/Roadmap) as a future improvement.

> android:icon="myicon"is also present at com.github.worker8:tourguide:1.0.10-SNAPSHOT:13:9 value=(@drawable/ic_launcher1)

I've heard other users reporting this too, but I couldn't reproduce it. I'm trying to find out what's wrong, do you have a drawable called `ic_launcher1` in your project? I might just rename it to something else.

> Your last point

Currently there is no better way to handle through TourGuide, so what you're doing is needed. I will improve this when I have time.

**Comment by MHDante** [comment] 2015-07-16 06:50
As a temporary fix for the Icon problem, add the following line to your Manifest in the `<manifest>`tag:

```
xmlns:tools="http://schemas.android.com/tools"
```

Then add the following to the `<application>` tag:

```
tools:replace="android:icon"
```

then re-build your app.

**Comment by defaultbr** [comment] 2015-07-16 14:14
@worker8 yes, exactly like the image you posted: 

https://camo.githubusercontent.com/4355d5d11e92c21ae63b9803fed4bc63f093f2f8/687474703a2f2f692e696d6775722e636f6d2f663544694c4e782e706e67

the pointer to the Top Guy got a overlay from the Bottom guy, or vice-versa imagining that the bottom guy should be the next button...

if you accept as an idea, tour.addTour(new TourGuide....), tour.nextTour() and tour.isLastTour() would be very helpfull, thanksss =)

and about the icon, no matter the name of the icon, i tried a several names, the problem is the tag android:icon, i think you need to remove the tag from the TourGuide, so it will automatically use the only one from user manifest, or we can use the android:replace like MHDante said

@MHDante lol, thank you so much, i really tried that before and dont worked, now it worked o0!! thanks

**Comment by worker8** [comment] 2015-08-07 04:34
The icon issue should be fixed and merged into the latest master. Regarding the next tour feature, it's a good idea! It's currently under development by @aaronliew [in this pull request](https://github.com/worker8/TourGuide/pull/22).

I will close this issue and the tracking/discussion of the development of running in sequence feature will go under the pull request page. And I added a to the todo list [here](https://github.com/worker8/TourGuide/wiki/Roadmap#tourguide-class-itself) for `setFirstTimeUser()` feature.

**Closed as completed by worker8** 2015-08-07 04:34 UTC
